# Generated by Django 4.2.14 on 2024-07-11 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('track', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='hour',
            field=models.DateTimeField(verbose_name='Heure'),
        ),
    ]
