# Generated by Django 4.2.14 on 2024-07-11 14:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('track', '0003_alter_customuser_options_customuser_full_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='track.department', verbose_name='Département'),
        ),
    ]
