# Generated by Django 4.2.14 on 2024-07-16 16:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('track', '0004_customuser_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='shift',
            field=models.CharField(choices=[('A', 'Shift A'), ('B', 'Shift B'), ('N', 'Shift N')], max_length=20, verbose_name='Shift'),
        ),
        migrations.CreateModel(
            name='Metric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric_name', models.CharField(max_length=100)),
                ('value', models.FloatField()),
                ('date', models.DateField()),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='track.department')),
            ],
        ),
    ]
