# Generated by Django 4.2.14 on 2024-07-20 13:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('track', '0005_alter_record_shift_metric'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='shift',
            field=models.CharField(choices=[('A', 'Shift A'), ('B', 'Shift B'), ('N', 'Shift N')], max_length=1, verbose_name='Shift'),
        ),
        migrations.CreateModel(
            name='ProductionData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shift', models.CharField(choices=[('A', 'Shift A'), ('B', 'Shift B'), ('N', 'Shift N')], max_length=1)),
                ('hour', models.IntegerField()),
                ('number_of_products', models.IntegerField()),
                ('calculated_loss', models.IntegerField()),
                ('logistic_loss', models.IntegerField()),
                ('logistic_comment', models.TextField(blank=True, null=True)),
                ('production_loss', models.IntegerField()),
                ('production_comment', models.TextField(blank=True, null=True)),
                ('uep', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='track.uep')),
            ],
        ),
    ]
