# Generated by Django 4.2.14 on 2024-07-22 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('track', '0006_alter_record_shift_productiondata'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductionData',
        ),
    ]
