# Generated by Django 4.2.14 on 2024-07-27 17:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('track', '0007_delete_productiondata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='track.department', verbose_name='Département'),
        ),
        migrations.AlterField(
            model_name='loss',
            name='record',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='losses', to='track.record', verbose_name='Enregistrement'),
        ),
        migrations.AlterField(
            model_name='metric',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='track.department'),
        ),
        migrations.AlterField(
            model_name='record',
            name='uep',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='track.uep', verbose_name='UEP'),
        ),
        migrations.AlterField(
            model_name='record',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur'),
        ),
        migrations.AlterField(
            model_name='uep',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ueps', to='track.department', verbose_name='Département'),
        ),
        migrations.AlterField(
            model_name='uep',
            name='target',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ueps', to='track.goal', verbose_name='Objectif'),
        ),
        migrations.AlterUniqueTogether(
            name='metric',
            unique_together={('department', 'metric_name', 'date')},
        ),
    ]
