# Generated by Django 4.2.14 on 2024-07-27 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('track', '0008_alter_customuser_department_alter_loss_record_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='shift',
            field=models.CharField(choices=[('A', 'shiftA'), ('B', 'shiftB'), ('N', 'shiftN')], max_length=1, verbose_name='Shift'),
        ),
    ]
