# Generated by Django 4.2.14 on 2024-07-31 13:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('track', '0009_alter_record_shift'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loss',
            name='logistic_comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='loss',
            name='logistic_loss',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='loss',
            name='production_comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='loss',
            name='production_loss',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='loss',
            name='record',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='losses', to='track.record'),
        ),
        migrations.AlterField(
            model_name='record',
            name='hour',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='record',
            name='number_of_products',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='record',
            name='shift',
            field=models.CharField(choices=[('A', 'Shift A'), ('B', 'Shift B'), ('N', 'Shift N')], max_length=1),
        ),
        migrations.AlterField(
            model_name='record',
            name='uep',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='track.uep'),
        ),
        migrations.AlterField(
            model_name='record',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
