# Generated by Django 4.2.14 on 2024-08-05 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('track', '0010_alter_loss_logistic_comment_alter_loss_logistic_loss_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loss',
            name='logistic_comment',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='loss',
            name='logistic_loss',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='loss',
            name='production_comment',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='loss',
            name='production_loss',
            field=models.FloatField(default=0),
        ),
        migrations.AlterUniqueTogether(
            name='record',
            unique_together={('user', 'shift', 'hour', 'uep')},
        ),
    ]
