# Generated by Django 4.2.14 on 2024-08-10 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('track', '0011_alter_loss_logistic_comment_alter_loss_logistic_loss_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='break_goal',
            field=models.JSONField(blank=True, default=dict, null=True, verbose_name='Objectif de pause'),
        ),
    ]
