# Generated by Django 4.2.14 on 2024-08-23 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('track', '0013_remove_goal_break_goal'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loss',
            old_name='logistic_loss',
            new_name='RoP',
        ),
        migrations.RenameField(
            model_name='loss',
            old_name='logistic_comment',
            new_name='RoP_comment',
        ),
        migrations.RenameField(
            model_name='loss',
            old_name='production_loss',
            new_name='saturation_manque',
        ),
        migrations.RenameField(
            model_name='loss',
            old_name='production_comment',
            new_name='saturation_manque_comment',
        ),
        migrations.AddField(
            model_name='loss',
            name='RoP_type',
            field=models.CharField(choices=[('LOG/MANCAISSE', 'LOG/MANCAISSE'), ('ANDON/FAB', 'ANDON/FAB'), ('MAI', 'MAI')], default='LOG/MANCAISSE', max_length=50),
        ),
        migrations.AddField(
            model_name='loss',
            name='saturation_manque_type',
            field=models.CharField(choices=[('Produit/Process', 'Produit/Process'), ('Saturation', 'Saturation')], default='Produit/Process', max_length=50),
        ),
    ]
